SuppliedPartx.project_class = 'HeavyMachineryProjectx::Project'
SuppliedPartx.customer_class = 'Kustomerx::Customer'
SuppliedPartx.supplier_class = 'Supplierx::Supplier'
SuppliedPartx.manufacturer_class = 'Manufacturerx::Manufacturer'
SuppliedPartx.show_project_path = 'heavy_machinery_projectx.project_path(r.project_id)'
SuppliedPartx.show_customer_path = 'kustomerx.customer_path(r.customer_id)'
SuppliedPartx.show_supplier_path = 'supplierx.supplier_path(r.supplier_id)'
